apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: app
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/sachumm127/test-app-argo.git'
    targetRevision: HEAD
    path: 'app'  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
