apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: app
  labels:
    app: myapp
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/myapp.allow-tags: "regexp:^build-[0-9]+$"  # Allow any build tag like build-25, build-26, etc.
    argocd-image-updater.argoproj.io/image-list: "myapp=343218199136.dkr.ecr.us-east-1.amazonaws.com/myapp:build-25"  # Specify the image tag here
    argocd-image-updater.argoproj.io/update-strategy: "newest-build"  # Will update the image to the newest build
    argocd-image-updater.argoproj.io/myapp.pull-secret: "pullsecret:app/ecr-secret"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: ecr-secret  # Ensure this secret exists and is configured correctly for ECR access
      containers:
        - name: myapp
          image: "343218199136.dkr.ecr.us-east-1.amazonaws.com/myapp:build-25"  # Ensure the correct tag is used here
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: aws-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
