# deployment.yaml - Simple deployment for Minikube
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: app
  labels:
    app: myapp
  annotations:
    # ArgoCD Image Updater annotations - this is where the magic happens
    argocd-image-updater.argoproj.io/image-list: "myapp=123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp"
    argocd-image-updater.argoproj.io/update-strategy: "latest"
    argocd-image-updater.argoproj.io/myapp.pull-secret: "pullsecret:app/ecr-secret"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: myapp
          image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:db3491104e5efb6724b1199088ff355a7bad0947"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: aws-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
# service.yaml - Simple service
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: app
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myapp
