apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  # IMPORTANT: This annotation tells ArgoCD to enable image updater for this app
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=343218199136.dkr.ecr.us-east-1.amazonaws.com/myapp
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest-tag
    argocd-image-updater.argoproj.io/myapp.allow-tags: ^build-[0-9]+$
spec:
  project: default
  source:
    repoURL: 
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
