apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=343218199136.dkr.ecr.us-east-1.amazonaws.com/myapp
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: k8s/deployment.yaml
    argocd-image-updater.argoproj.io/myapp.write-back-target: k8s/deployment.yaml
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^build-[0-9]+$
    argocd-image-updater.argoproj.io/myapp.pull-secret: pullsecret:argocd/ecr-secret
    argocd-image-updater.argoproj.io/log.level: debug  # for debugging
spec:
  project: default
  source:
    repoURL: https://github.com/sachumm127/test-app-argo.git
    targetRevision: HEAD
    path: k8s
    kustomize: {}  # This enables Kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
